//
// Created by Ko-chieh Yin on 9/28/25.
//

#ifndef DISTRIBUTED_LOCK_DEMO_COMMANDNOTSUPPORTEXCEPTION_H
#define DISTRIBUTED_LOCK_DEMO_COMMANDNOTSUPPORTEXCEPTION_H

#endif //DISTRIBUTED_LOCK_DEMO_COMMANDNOTSUPPORTEXCEPTION_H